### ISSUE TITLE
How do we get a surface from a tensor image?

### ISSUE THREAD

**Issue by andreirusu** [google-deepmind/torch-oocairo#1]
Nice having an rgb2tensor function!
Is there a tensor2surface/rgb function?

**Comment by akfidjeland** [comment]
@andreirusu : yes, this function was missing. Added tensor2rgb24 in cdb53093f219a24a5fb4e3ba13595347d04fd05f. It assumes 1- or 3-channel inputs in the range [0,1] with some of the options used by image.display (saturate, min, max, symmetric).
